/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.panels;

import java.util.List;
import metier.entities.*;
import static presentation.panels.Authentification_Form.EMPLOYE;

/**
 *
 * @author CY_15
 */
public class Acceuil extends javax.swing.JPanel {    
    public Acceuil() 
    {
        initComponents();
        jLabel2.setText("Numéro d'employé :   "+EMPLOYE.getNumEmploye());
        jLabel3.setText("Nom d'employé      :  "+EMPLOYE.getNomEmploye());
        if(EMPLOYE.getSupHierarchique()==null)
            jLabel1.setVisible(false);
        else
            jLabel1.setText("Supérieure            :  "+EMPLOYE.getSupHierarchique().getNomEmploye());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(973, 558));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supérieure            :  YYYY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numéro d'employé :   0000");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'employé      :  XXXX");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 230, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/bbb.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 70, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/eb.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
