/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.panels;

import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import metier.entities.*;
import static presentation.panels.Authentification_Form.*;

/**
 *
 * @author CY_15
 */
public class operations extends javax.swing.JPanel {

    List<Compte> listeComptes;
    
    public operations() 
    {
        initComponents();
        
        /* Remplire la table */
        DefaultTableModel model = (DefaultTableModel) tablesComptes.getModel();
        while (model.getRowCount() > 0) model.removeRow(0);
        listeComptes = eBanque.consulterComptes();
        for(Compte c : listeComptes)
        {   
            String numCompte = c.getNumCompte();
            Double s = c.getSolde();
            Object decouvert=null;
            Object taux=null;
            if(c instanceof CompteCourant)
            {
                CompteCourant cc = (CompteCourant)c;
                decouvert = cc.getDecouvert();
            }
            else
            {
                CompteEpargne ce = (CompteEpargne)c;
                taux = ce.getTaux();
            }  
            Date d = c.getDateCreation();
            Long numEmp = c.getEmploye().getNumEmploye();
            Long codeClient = c.getClient().getCodeClient();
            model.addRow(new Object[]{numCompte, s, taux, decouvert, d, codeClient, numEmp});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesComptes = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codeClientTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comptesComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        NomClientLabel = new javax.swing.JLabel();
        verserButton = new javax.swing.JButton();
        montantTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        codeClientTextBox1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comptesComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        NomClientLabel1 = new javax.swing.JLabel();
        retirerButton = new javax.swing.JButton();
        montantTextBox1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        codeClientTextBox2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comptesComboBox2 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        NomClientLabel2 = new javax.swing.JLabel();
        tranfererButton = new javax.swing.JButton();
        montantTextBox2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        codeClientTextBox3 = new javax.swing.JTextField();
        comptesComboBox3 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        NomClientLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(973, 558));

        jTabbedPane1.setBackground(new java.awt.Color(51, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 51));
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        jTabbedPane6.setBackground(new java.awt.Color(51, 0, 51));
        jTabbedPane6.setForeground(new java.awt.Color(51, 0, 0));

        tablesComptes.setAutoCreateRowSorter(true);
        tablesComptes.setBackground(new java.awt.Color(51, 0, 0));
        tablesComptes.setForeground(new java.awt.Color(255, 255, 255));
        tablesComptes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Solde", "Taux", "Decouvert", "Date de création", "Client", "Crée par (Employé)"
            }
        ));
        tablesComptes.setFillsViewportHeight(true);
        tablesComptes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablesComptes);

        jTabbedPane6.addTab("Les informations des comptes", jScrollPane1);

        jTabbedPane1.addTab("Comptes", new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/credit-cards-payment.png")), jTabbedPane6); // NOI18N
        jTabbedPane6.getAccessibleContext().setAccessibleName("Les informations des comptes");

        jTabbedPane4.setBackground(new java.awt.Color(51, 0, 0));
        jTabbedPane4.setForeground(new java.awt.Color(51, 0, 51));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 0, 0));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Compte       :");

        codeClientTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeClientTextBoxKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Montant      :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel4.setText("DH");
        jLabel4.setEnabled(false);

        comptesComboBox.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel3.setText("*Code client");
        jLabel3.setEnabled(false);

        NomClientLabel.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        NomClientLabel.setEnabled(false);

        verserButton.setBackground(new java.awt.Color(51, 0, 0));
        verserButton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        verserButton.setForeground(new java.awt.Color(255, 255, 255));
        verserButton.setText("Verser");
        verserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        verserButton.setContentAreaFilled(false);
        verserButton.setOpaque(true);
        verserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verserButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verserButtonMouseReleased(evt);
            }
        });
        verserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verserButtonActionPerformed(evt);
            }
        });

        montantTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montantTextBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(montantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(comptesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(codeClientTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(NomClientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comptesComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeClientTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomClientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/get-money.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel5)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("", jPanel1);

        jTabbedPane1.addTab("Versement", new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/payment-method.png")), jTabbedPane4); // NOI18N

        jTabbedPane3.setBackground(new java.awt.Color(51, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        jPanel5.setBackground(new java.awt.Color(51, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Compte       :");

        codeClientTextBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeClientTextBox1KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Montant      :");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel8.setText("DH");
        jLabel8.setEnabled(false);

        comptesComboBox1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel9.setText("*Code client");
        jLabel9.setEnabled(false);

        NomClientLabel1.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        NomClientLabel1.setEnabled(false);

        retirerButton.setBackground(new java.awt.Color(51, 0, 0));
        retirerButton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        retirerButton.setForeground(new java.awt.Color(255, 255, 255));
        retirerButton.setText("Retirer");
        retirerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        retirerButton.setContentAreaFilled(false);
        retirerButton.setOpaque(true);
        retirerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retirerButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                retirerButtonMouseReleased(evt);
            }
        });
        retirerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerButtonActionPerformed(evt);
            }
        });

        montantTextBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montantTextBox1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retirerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(montantTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(comptesComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(codeClientTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(NomClientLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montantTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comptesComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeClientTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomClientLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retirerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/profits.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 133, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("", jPanel2);

        jTabbedPane1.addTab("    Retrait", new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/give-money.png")), jTabbedPane3); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        jPanel6.setBackground(new java.awt.Color(51, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Compte source        :");

        codeClientTextBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeClientTextBox2KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Montant                  :");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel13.setText("DH");
        jLabel13.setEnabled(false);

        comptesComboBox2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel14.setText("*Code client");
        jLabel14.setEnabled(false);

        NomClientLabel2.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        NomClientLabel2.setEnabled(false);

        tranfererButton.setBackground(new java.awt.Color(204, 204, 204));
        tranfererButton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tranfererButton.setForeground(new java.awt.Color(255, 255, 255));
        tranfererButton.setText("Transferer");
        tranfererButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tranfererButton.setContentAreaFilled(false);
        tranfererButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tranfererButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tranfererButtonMouseReleased(evt);
            }
        });
        tranfererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranfererButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jLabel16.setText("*Code client");
        jLabel16.setEnabled(false);

        codeClientTextBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeClientTextBox3KeyReleased(evt);
            }
        });

        comptesComboBox3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Compte destinataire  :");

        NomClientLabel3.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        NomClientLabel3.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(comptesComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codeClientTextBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(tranfererButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(montantTextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(comptesComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(codeClientTextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addComponent(NomClientLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NomClientLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(montantTextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comptesComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeClientTextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomClientLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeClientTextBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comptesComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomClientLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(tranfererButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/transaction.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel15)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("", jPanel3);

        jTabbedPane1.addTab("    Virement", new javax.swing.ImageIcon(getClass().getResource("/presentation/media/icons/transfer.png")), jTabbedPane2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        int index = jTabbedPane1.getSelectedIndex();
        if(index == 0)
        {
            /* Remplire la table */
            DefaultTableModel model = (DefaultTableModel) tablesComptes.getModel();
            while (model.getRowCount() > 0) model.removeRow(0);
            listeComptes = eBanque.consulterComptes();
            for(Compte c : listeComptes)
            {   
                String numCompte = c.getNumCompte();
                Double s = c.getSolde();
                Object decouvert=null;
                Object taux=null;
                if(c instanceof CompteCourant)
                {
                    CompteCourant cc = (CompteCourant)c;
                    decouvert = cc.getDecouvert();
                }
                else
                {
                    CompteEpargne ce = (CompteEpargne)c;
                    taux = ce.getTaux();
                }  
                Date d = c.getDateCreation();
                Long numEmp = c.getEmploye().getNumEmploye();
                Long codeClient = c.getClient().getCodeClient();
                model.addRow(new Object[]{numCompte, s, taux, decouvert, d, codeClient, numEmp});
            }
        }
        else if(index == 1)
        {
            comptesComboBox.removeAllItems();
            listeComptes = eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox.addItem(c.getNumCompte());
        }
        else if(index == 2)
        {
            comptesComboBox1.removeAllItems();
            listeComptes = eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox1.addItem(c.getNumCompte());
        }
        else if(index == 3)
        {
            listeComptes = eBanque.consulterComptes();
            comptesComboBox2.removeAllItems();
            comptesComboBox3.removeAllItems();
            for(Compte c : listeComptes)
            {
                comptesComboBox2.addItem(c.getNumCompte());
                comptesComboBox3.addItem(c.getNumCompte());
            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void verserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verserButtonActionPerformed
        try
        {   
            Double mnt = Math.abs(Double.parseDouble(montantTextBox.getText()));
            if(comptesComboBox.getSelectedIndex()<0)
            {
                JOptionPane.showMessageDialog(null, "\nVeuillez choisir un compte !\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String compte = comptesComboBox.getSelectedItem().toString();
            Operation opV = new Versement(new Date(), mnt);
            eBanque.addOperation(opV, compte, EMPLOYE.getNumEmploye());
            montantTextBox.setText("");
            codeClientTextBox.setText("");
            JOptionPane.showMessageDialog(null, "\nL'opération de versement est passée avec succes.\n\n", "INFO", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(NumberFormatException ex)
        {
            montantTextBox.setForeground(Color.WHITE);
            montantTextBox.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "\nVeuillez saisir un réel pour le montant.\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
            montantTextBox.setText("");
        }        
    }//GEN-LAST:event_verserButtonActionPerformed

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
    }//GEN-LAST:event_jTabbedPane1PropertyChange

    private void codeClientTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeClientTextBoxKeyReleased
        if(codeClientTextBox.getText().isEmpty())
        {   
            codeClientTextBox.setForeground(Color.BLACK);
            codeClientTextBox.setBackground(Color.WHITE);
            NomClientLabel.setText("");
            comptesComboBox.removeAllItems();
            listeComptes = Authentification_Form.eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox.addItem(c.getNumCompte());
        }
        else
        {   
            try
            {   
                codeClientTextBox.setForeground(Color.BLACK);
                codeClientTextBox.setBackground(Color.WHITE);
                Long codeClient = Long.parseLong(codeClientTextBox.getText());
                comptesComboBox.removeAllItems();
                Client cl = eBanque.consulterClient(codeClient);
                NomClientLabel.setText(cl.getNomClient());
                listeComptes = cl.getComptes();
                for(Compte c : listeComptes)
                    comptesComboBox.addItem(c.getNumCompte());
            }
            catch(NumberFormatException ex)
            {   
                codeClientTextBox.setForeground(Color.WHITE);
                codeClientTextBox.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "\nVeuillez saisir un nombre.\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                NomClientLabel.setText("");
                codeClientTextBox.setForeground(Color.BLACK);
                codeClientTextBox.setBackground(Color.WHITE);
            }
            catch(RuntimeException ex)
            {   
                NomClientLabel.setText("");
                codeClientTextBox.setForeground(Color.WHITE);
                codeClientTextBox.setBackground(Color.RED);
            }
        }
        
    }//GEN-LAST:event_codeClientTextBoxKeyReleased

    private void codeClientTextBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeClientTextBox1KeyReleased
        if(codeClientTextBox1.getText().isEmpty())
        {   
            codeClientTextBox1.setForeground(Color.BLACK);
            codeClientTextBox1.setBackground(Color.WHITE);
            NomClientLabel1.setText("");
            comptesComboBox1.removeAllItems();
            listeComptes = Authentification_Form.eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox1.addItem(c.getNumCompte());
        }
        else
        {   
            try
            {   
                codeClientTextBox1.setForeground(Color.BLACK);
                codeClientTextBox1.setBackground(Color.WHITE);
                Long codeClient = Long.parseLong(codeClientTextBox1.getText());
                comptesComboBox1.removeAllItems();
                Client cl = eBanque.consulterClient(codeClient);
                NomClientLabel1.setText(cl.getNomClient());
                listeComptes = cl.getComptes();
                for(Compte c : listeComptes)
                    comptesComboBox1.addItem(c.getNumCompte());
            }
            catch(java.lang.NumberFormatException ex)
            {   
                codeClientTextBox1.setForeground(Color.WHITE);
                codeClientTextBox1.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "\nVeuillez saisir un nombre.\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                NomClientLabel1.setText("");
                codeClientTextBox1.setForeground(Color.BLACK);
                codeClientTextBox1.setBackground(Color.WHITE);
            }
            catch(RuntimeException ex)
            {   
                NomClientLabel1.setText("");
                codeClientTextBox1.setForeground(Color.WHITE);
                codeClientTextBox1.setBackground(Color.RED);
            }
        }
    }//GEN-LAST:event_codeClientTextBox1KeyReleased

    private void retirerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerButtonActionPerformed
        try
        {   
            Double mnt = Math.abs(Double.parseDouble(montantTextBox1.getText()));
            if(comptesComboBox1.getSelectedIndex()<0)
            {
                JOptionPane.showMessageDialog(null, "\nVeuillez choisir un compte !\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String compte = comptesComboBox1.getSelectedItem().toString();
            try
            {
                Operation opV = new Retrait(new Date(), mnt);
                eBanque.addOperation(opV, compte, EMPLOYE.getNumEmploye());
                JOptionPane.showMessageDialog(null, "\nL'opération de retrait est passée avec succes.\n\n", "INFO", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(RuntimeException ex)
            {
                JOptionPane.showMessageDialog(null, "\nL'opération de retrait n'est pas passée!\nCar le solde du compte est insuffisant.\n\n", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            }
            montantTextBox1.setText("");
            codeClientTextBox1.setText("");
        }
        catch(NumberFormatException ex)
        {
            montantTextBox1.setForeground(Color.WHITE);
            montantTextBox1.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "\nVeuillez saisir un réel pour le montant.\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
            montantTextBox1.setText("");
        }
    }//GEN-LAST:event_retirerButtonActionPerformed

    private void codeClientTextBox2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeClientTextBox2KeyReleased
        if(codeClientTextBox2.getText().isEmpty())
        {   
            codeClientTextBox2.setForeground(Color.BLACK);
            codeClientTextBox2.setBackground(Color.WHITE);
            NomClientLabel2.setText("");
            comptesComboBox2.removeAllItems();
            listeComptes = Authentification_Form.eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox2.addItem(c.getNumCompte());
        }
        else
        {   
            try
            {   
                codeClientTextBox2.setForeground(Color.BLACK);
                codeClientTextBox2.setBackground(Color.WHITE);
                Long codeClient = Long.parseLong(codeClientTextBox2.getText());
                comptesComboBox2.removeAllItems();
                Client cl = eBanque.consulterClient(codeClient);
                NomClientLabel2.setText(cl.getNomClient());
                listeComptes = cl.getComptes();
                for(Compte c : listeComptes)
                    comptesComboBox2.addItem(c.getNumCompte());
            }
            catch(java.lang.NumberFormatException ex)
            {   
                codeClientTextBox2.setForeground(Color.WHITE);
                codeClientTextBox2.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "\nVeuillez saisir un nombre.\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                NomClientLabel2.setText("");
                codeClientTextBox2.setForeground(Color.BLACK);
                codeClientTextBox2.setBackground(Color.WHITE);
            }
            catch(RuntimeException ex)
            {   
                NomClientLabel2.setText("");
                codeClientTextBox2.setForeground(Color.WHITE);
                codeClientTextBox2.setBackground(Color.RED);
            }
        }
    }//GEN-LAST:event_codeClientTextBox2KeyReleased

    private void tranfererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranfererButtonActionPerformed
        try
        {
            Double mnt = Math.abs(Double.parseDouble(montantTextBox2.getText()));
            if(comptesComboBox2.getSelectedIndex()<0)
            {
                JOptionPane.showMessageDialog(null, "\nVeuillez saisir une compte !\n\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String compteSource = comptesComboBox2.getSelectedItem().toString();
            String compteDestinataire = comptesComboBox3.getSelectedItem().toString();
            Long numEmp = EMPLOYE.getNumEmploye();
            try
            {   
                /* Retrait */
                Operation opR = new Retrait(new Date(), mnt);
                eBanque.addOperation(opR, compteSource, numEmp);

                /* Versement */
                Operation opV = new Versement(new Date(), mnt);
                eBanque.addOperation(opV, compteDestinataire, numEmp);
                
                JOptionPane.showMessageDialog(null, "\nL'opération du virement est passée avec succes.\n", "INFO", JOptionPane.INFORMATION_MESSAGE);
                montantTextBox2.setText("");
            }
            catch(RuntimeException ex)
            {
                JOptionPane.showMessageDialog(null, "\nL'opération du virement n'a pas passée !\nCar le solde du compte est insuffisant.\n\n", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            }
            montantTextBox1.setText("");
            codeClientTextBox1.setText("");
        }
        catch(NumberFormatException ex)
        {
            montantTextBox.setForeground(Color.WHITE);
            montantTextBox.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "\nVeuillez saisir un réel pour le montant.\n", "ATTENTION", JOptionPane.WARNING_MESSAGE);
            montantTextBox.setText("");
        }
    }//GEN-LAST:event_tranfererButtonActionPerformed

    private void codeClientTextBox3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeClientTextBox3KeyReleased
        if(codeClientTextBox3.getText().isEmpty())
        {   
            codeClientTextBox3.setForeground(Color.BLACK);
            codeClientTextBox3.setBackground(Color.WHITE);
            NomClientLabel3.setText("");
            comptesComboBox3.removeAllItems();
            listeComptes = Authentification_Form.eBanque.consulterComptes();
            for(Compte c : listeComptes)
                comptesComboBox3.addItem(c.getNumCompte());
        }
        else
        {   
            try
            {   
                codeClientTextBox3.setForeground(Color.BLACK);
                codeClientTextBox3.setBackground(Color.WHITE);
                Long codeClient = Long.parseLong(codeClientTextBox3.getText());
                comptesComboBox3.removeAllItems();
                Client cl = eBanque.consulterClient(codeClient);
                NomClientLabel3.setText(cl.getNomClient());
                listeComptes = cl.getComptes();
                for(Compte c : listeComptes)
                    comptesComboBox3.addItem(c.getNumCompte());
            }
            catch(NumberFormatException ex)
            {   
                codeClientTextBox3.setForeground(Color.WHITE);
                codeClientTextBox3.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "Veuillez saisir un nombre 'Long'", "ATTENTION", JOptionPane.WARNING_MESSAGE);
                NomClientLabel3.setText("");
                codeClientTextBox3.setForeground(Color.BLACK);
                codeClientTextBox3.setBackground(Color.WHITE);
            }
            catch(RuntimeException ex)
            {   
                NomClientLabel3.setText("");
                codeClientTextBox3.setForeground(Color.WHITE);
                codeClientTextBox3.setBackground(Color.RED);
            }
        }
    }//GEN-LAST:event_codeClientTextBox3KeyReleased

    private void montantTextBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montantTextBox1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_montantTextBox1KeyReleased

    private void montantTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montantTextBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_montantTextBoxKeyReleased

    private void verserButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verserButtonMousePressed
        verserButton.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_verserButtonMousePressed

    private void verserButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verserButtonMouseReleased
        verserButton.setBackground(new Color(51,0,0));
    }//GEN-LAST:event_verserButtonMouseReleased

    private void retirerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirerButtonMousePressed
        retirerButton.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_retirerButtonMousePressed

    private void retirerButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirerButtonMouseReleased
        retirerButton.setBackground(new Color(51,0,0));
    }//GEN-LAST:event_retirerButtonMouseReleased

    private void tranfererButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tranfererButtonMousePressed
        tranfererButton.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_tranfererButtonMousePressed

    private void tranfererButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tranfererButtonMouseReleased
        tranfererButton.setBackground(new Color(51,0,0));
    }//GEN-LAST:event_tranfererButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomClientLabel;
    private javax.swing.JLabel NomClientLabel1;
    private javax.swing.JLabel NomClientLabel2;
    private javax.swing.JLabel NomClientLabel3;
    private javax.swing.JTextField codeClientTextBox;
    private javax.swing.JTextField codeClientTextBox1;
    private javax.swing.JTextField codeClientTextBox2;
    private javax.swing.JTextField codeClientTextBox3;
    private javax.swing.JComboBox comptesComboBox;
    private javax.swing.JComboBox comptesComboBox1;
    private javax.swing.JComboBox comptesComboBox2;
    private javax.swing.JComboBox comptesComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField montantTextBox;
    private javax.swing.JTextField montantTextBox1;
    private javax.swing.JTextField montantTextBox2;
    private javax.swing.JButton retirerButton;
    public static javax.swing.JTable tablesComptes;
    private javax.swing.JButton tranfererButton;
    private javax.swing.JButton verserButton;
    // End of variables declaration//GEN-END:variables
}
